<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>CV Anastassiya Pagnoux-Page erreur</title>
		<meta name="description" content="Anastassiya Pagnoux - Integrateur Développeur Web : HTML 5, CSS 3, WordPress, Bootstrap, JS, JAVA JEE (programmation orientée objet), PHP (POO), MySQL. Formation initiale Doctorat en chimie - pilotage d’un projet de recherche." />
		<meta name="robots" content="index, follow" >
		<link rel="stylesheet" type="text/css" href="css/font-awesome.min.css">
		<link rel="stylesheet" type="text/css" href="css/normalize.css">
		<link rel="stylesheet" type="text/css" href="css/style.css">
	</head>
	<body>
    <section>
      <h1>Il semble que cette page n'existe pas</h1>
    </section>
  </body>
</html>
