<?php $pRubrique = 'Expérience Professionelle'; ?>
<?php include 'header.phtml'; ?>
<main class = "container">
  <section>
    <h1>Expérience Professionelle</h1>
    <ul class="titreGras espace" >
      <li>01-05/2018 CONSULTANT JUNIOR - SOPRA HR à La Défense</li>
      <li>Paramétrage personnalisé de logiciel de gestion « Pléiades » </li>
      <li>Création des fonctions et des conditions en NGScript</li>
      <li>Interrogation de la base de donnés Oracle avec le SQL </li>
      <li>Chiffrage et réalisation d'un dévie pour les prestations associés</li>
    </ul>

    <ul class="titreGras espace">
      <li>06-09/17 FORMATION DEVELOPPEUR INTEGRATEUR WEB - «3W Academy» - 90% de pratique</li>
      <li>Réalisation de 14 maquettes de sites WEB :</li>
      <li>HTML 5, CSS 3, Bootstrap, WordPress</li>
      <li>Conception des 21 projets de développement WEB : </li>
      <li>Java Script Programmation Orienté Objet, Viu JS, JQuery, AJAX, PHP POO, SQL, Canvas, SVG</li>
    </ul>

    <ul class="titreGras espace">
      <li>09/16-02/17 TECHNICIEN CONTROLE QUALITÉ AGRO-ALIMENTAIRE ISHA</li>
      <li class="italic">Institut Scientifique d'Hygiène et d'Analyse à Champlan</li>
      <li>Chimie Agroalimentaire : analyse des vitamines C, D, B et de la matière sèche</li>
      <li>Rédaction d’un compte rendu d’analyse</li>
    </ul>

    <ul class="titreGras espace">
      <li>11/14-09/16 ANIMATRICE TAP - Mairie de Voisins-le-Bretonneux (écoles primaires)</li>
      <li>« Expériences de la chimie amusante » pour les enfants de CP à CM2</li>
      <li>Création de supports visuels (Photoshop)</li>
      <li>Soutien scolaire en groupe, cours particuliers</li>
    </ul>

    <ul class="titreGras espace">
      <li>03-11/14 POST-DOCTORANT - CNRS OMC  Université de Rennes</li>
      <li>Synthèse et caractérisation des ligands tagués et des complexes de ruthénium.</li>
      <li>Collaboration entre les universités Rennes-Orsay-Caen.</li>
      <li>1 Publication scientifique</li>
    </ul>

    <ul class="titreGras espace">
      <li>09/13-01/14 TECHNICIEN CONTROLE QUALITÉ PHARMACEUTIQUE</li>
      <li class="italic">Laboratoire FARMACLAIR Groupe Fareva - Hérouville St-Clair</li>
      <li>Contrôle qualité des produits finis pharmaceutiques et cosmétiques.</li>
      <li>Rédaction d’un compte rendu d’analyse</li>
    </ul>

    <ul class="titreGras espace">
      <li>2009-2012 DOCTORAT - LCMT  Université de Caen</li>
      <li>Synthèse et étude de l'activité des complexes de fer</li>
      <li>Définition de l’axe de recherche : analyse de contrainte de méthode : </li>
      <li class="italic">coût, temps, éco-compatibilité</li>
      <li>Proposition de stratégies de synthèse et des solutions d’optimisation</li>
      <li>3 Publications scientifiques</li>
    </ul>
	</section>
</main>
<?php include 'footer.phtml'; ?>
