<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="Anastassiya Pagnoux - Integrateur Développeur Web : HTML 5, CSS 3, WordPress, Bootstrap, JS, JAVA JEE (programmation orientée objet), PHP (POO), MySQL. Formation initiale Doctorat en chimie - pilotage d’un projet de recherche." />
		<meta name="robots" content="index, follow" >
		<link rel="stylesheet" type="text/css" href="css/font-awesome.min.css">
		<link rel="stylesheet" type="text/css" href="css/normalize.css">
		<link rel="stylesheet" type="text/css" href="css/style.css">
		<title>CV Anastassiya Pagnoux-<?=$pRubrique; ?></title>
	</head>
	<body>
		<div class="wrap">

		<header id="menu">
			<div>
				<p>Anastassiya Pagnoux</p>
			</div>
			<img src="img/logo4.png" alt="Integrateur Développeur Web" id="max" width="700">
			<img src="img/logoMobil.png" alt="Integrateur Développeur Web" id="min">
		</header>

		<nav class="container">
			<ul class="nav">
				<li><a href="index.php?page=accueil">Accueil</a></li><!--
			--><li><a href="index.php?page=experience-profesionnelle">Expérience Professionelle</a></li><!--
			--><li><a href="index.php?page=recherche">R&D-Chimie</a></li><!--
			--><li><a href="index.php?page=personalite">Personnalité</a></li>
			</ul>
		</nav>
