<?php $pRubrique = 'Accueil'; ?>
<?php include 'header.phtml'; ?>
<div class="wrapper">
<main id="accueil" class = "container">
  <section>
    <h1>Presentation et competences</h1>

    <aside class="encadrement">
      <p><cite>"Le plus beau des métiers, c'est de vivre de sa passion."</cite></p>
      <span>François Salvat de Montfort. Vasconiana ou recueil des bons mots (1708).</span>
    </aside>

    <div class="logos">
      <figure>
        <img src="img/logo-java.png" alt="Logo Java">
        <figcaption>Java et Java JEE (POO)</figcaption>
      </figure>

      <figure>
        <img src="img/logo-php.png" alt="Logo PHP">
        <figcaption>PHP (POO)</figcaption>
      </figure>

      <figure>
        <img src="img/logo-JS.png" alt="Logo Java Script">
        <figcaption>Java script (POO)</figcaption>
      </figure>

      <figure>
        <img src="img/logo-SQL.png" alt="Logo SQL">
        <figcaption>SQL</figcaption>
      </figure>

      <figure>
        <img src="img/logo-sopra-steria.png" alt="Logo Sopra-Steria">
        <figcaption>NG script</figcaption>
      </figure>

      <figure>
        <img src="img/logo-HTML5.png" alt="Logo HTML">
        <figcaption>HTML 5</figcaption>
      </figure>

      <figure>
        <img src="img/logo-CSS3.png" alt="Logo CSS">
        <figcaption>CSS 3</figcaption>
      </figure>

      <figure>
        <img src="img/logo-WordPress.png" alt="Logo WordPress">
        <figcaption>WordPress</figcaption>
      </figure>

      <figure>
        <img src="img/logo-bootstrap.png" alt="Logo Bootstrap">
        <figcaption>Bootstrap</figcaption>
      </figure>

      <figure>
        <img src="img/color-palette.png" alt="Symbole outilles graphiques">
        <figcaption>Photoshop, Gimp, Corel IPE5 et tablette graphique</figcaption>
      </figure>
    </div>

    <article class="encadrement">
      <h2>Faisons connaissance!</h2>

      <figure id="photo">
        <img src="img/photoAPagnoux.png" alt="photo Anastassiya Pagnoux">
      </figure>
      <p>Tout d'abord bonjour et Bienvenue sur mon site!</p>
      <p>Nous sommes en 2019 et la phrase de François Salvat de Montfort reste toujours aussi vraie n'est ce pas?</p>

      <p>Ma première passion c'était la chimie, l’intérêt pour la transformation de la matière m'a amené à soutenir une thèse, puis poursuivre avec le post-doctorat et après... La réalité est telle que les gens diplômés dans des domaines de biologie, chimie ou physique sont confrontés à un choix : quitter la belle France, accepter des postes inférieurs à leur formation, ou encore trouver une autre passion. Ayant essayé les trois options j'ai finalement choisi la dernière. </p>

      <p>Parmi tous les métiers existants, lequel deviendra pour moi le moteur pour avancer vers de nouveaux horizons? Mille merci aux membres de l'association AREA qui m'ont fait passer le test (Central Test) ProfilPro. Le résultat était incontestable - web-master à 81% de correspondance métier-personnalité. </p>

      <p>Le choix a été fait et la première réussite n'était pas loin - l'obtention du diplôme BTS (développeur Web avec 3W Academy), complété par la formation développeur JAVA JEE avec M2I que je suis actuellement.</p>

      <p class="clear">Mon profil vous intrigue? Je vous laisse, alors, découvrir les détails de l'histoire.</p>
    </article>

    <article class="espace">
      <h2>Formations</h2>
      <ul>
        <li><strong>2019 « DEVELOPPEUR JAVA JEE »</strong> Certificat à Rennes « M2I »</li>
        <li><a href="https://diplome.3wa.fr/pagnoux-anastassiya"><strong>2018 « DEVELOPPEUR INTEGRATEUR EN REALISATION D’APPLICATION WEB »</strong> RNCP 25468 (BTS) à Paris «3W Academy»</a></li>
        <li><strong>2016 « HPLC-UFLC appliquée aux Sciences du Vivant»</strong> Certificat Paris Diderot</li>
        <li><strong>2012 DOCTORAT</strong> à l’université de Caen : Chimie Organique Minérale, Industrielle</li>
        <li><strong>2009 MASTER</strong> à l’université de Versailles : Réactivité moléculaire et matériaux</li>
        <li><strong>2007 LICENCE</strong> à l’université de Versailles : Chimie Organique</li>
      </ul>
    </article>
  </section>
</main>
</div>

<?php include 'footer.phtml'; ?>
