<?php $pRubrique = 'Accueil'; ?>
<?php include 'header.phtml'; ?>
<main class = "container">
	<section>
	<h1>Profil</h1>
		<article>
		<h2>Rapport Central Test</h2>

		<p>Ici vous trouverez quelques points parmi les plus pertinents sur ma personnalité.</p>

		<p>Ces informations sont issues d'un rapport de profil pro 2 (central test) à la date du 04/12/2016.</p>

		<ul>
			<li>
				Spontanée et adaptable, Anastassiya PAGNOUX est connue pour sa facilité à improviser et à gérer les situations imprévues avec aisance.
			</li>
			<li>
				De nature altruiste, Anastassiya PAGNOUX est généreuse. Elle est toujours prête à tendre la main et aider les autres.
			</li>
			<li>
				Plutôt créative, Anastassiya PAGNOUX explore les nouvelles idées et méthodes. Elle aime tester les nouvelles pratiques.
			</li>
		</ul>
		</article>
	</section>

	<section>
		<article>
			<h3>Rationalisme / Intuition</h3>

			<p>Anastassiya PAGNOUX se fie principalement à la logique et aux faits afin de prendre des décisions et de résoudre les problèmes. Elle a plutôt tendance à examiner attentivement les informations et à analyser les détails d'un problème avant de prendre position. Anastassiya PAGNOUX a tendance à faire abstraction de son instinct et prend habituellement en compte la plupart des dimensions d'un problème.</p>

			<p>Environnement et fonctions : Les postes qui nécessitent de vérifier les faits afin de mener à bien les projets lui conviennent bien.</p>

			<p>Interaction avec les autres : Elle a tendance à encourager les membres de l'équipe à étudier les informations de façon approfondie avant toute prise de décision.</p>

			<p>Qualités : Elle analyse les faits avec circonspection et de façon détaillée.</p>

			<p>Limites potentielles : Elle risque de ne pas tenir compte de certaines intuitions susceptibles de s'avérer utiles.</p>
		</article><!--

		--><article>
			<h3>Respect des règles / Libre pensée</h3>

			<p>Anastassiya PAGNOUX se conforme scrupuleusement à l'ensemble des réglementations et des politiques institutionnelles. Les personnes présentant un score similaire pensent généralement que les règles et procédures n'ont pas vocation à être interprétées et qu'elles doivent être suivies sans exception. Anastassiya PAGNOUX a tendance à se conformer aux lignes directrices établies, puisque ses propres principes sont habituellement liés à ceux de l'organisation. Elle a tendance à être connue au sein de l'organisation pour sa méticulosité et son respect des procédures d'assurance qualité.</p>

			<p>Environnement et fonctions : Les postes nécessitant un strict respect des règles en raison des dangers associés à leur non-respect sont ceux qui lui conviennent le mieux.</p>

			<p>Interaction avec les autres : Elle a tendance à s'assurer que les membres de l'équipe se conforment aux règles.</p>

			<p>Qualités : Elle applique les réglementations pour des raisons de qualité ou de sécurité ou des raisons juridiques.</p>

			<p>Limites potentielles : Elle risque de ne pas remettre en question des règles dépassées ou inefficaces.</p>
		</article><!--

		--><article>
			<h3>Volonté de persuasion / Besoin d'objectivité : </h3>

			<p>Anastassiya PAGNOUX est franche et apprécie l'authenticité. Elle ne cherche pas à persuader ou à influencer les autres et préfère généralement présenter les informations de façon objective. Plutôt directe, Anastassiya PAGNOUX préfère dire les choses telles qu'elles sont. Elle ne cautionne pas le fait de tromper autrui et reste généralement fidèle à elle même.</p>

			<p>Environnement et fonctions : Les organisations qui mettent en valeur l'honnêteté dans les relations avec les clients ou entre collègues lui conviennent très bien.</p>

			<p>Interaction avec les autres : Elle a tendance à encourager les autres à être directs et ouverts dans leur façon de communiquer.</p>

			<p>Qualités : Elle est vrai dans ses relations et ses collègues ont tendance à faire appel à elle pour obtenir un avis sincère.</p>

			<p>Limites potentielles : L'importance qu'elle accorde à la transparence peut conduire à un moindre pouvoir de négociation.</p>

		</article>
	</section>


	<section>
		<h2>Centres d'Interet</h2>
		<article>
			<ul>
				<li>Arts martiaux - Aïkido, Capoeira...</li>
				<li>Traduction - Russe-Francais</li>
				<li>Peinture - huille, aquarelle</li>
				<li>Activités associatives - 2009 Présidente du club Aikido Yoshinkan, activités avec l'association culturelle Menestrel à Tarbes</li>
			</ul>
		</article>
	</section>
</main>
<?php include 'footer.phtml'; ?>
