<?php $pRubrique = 'Recherche et développement'; ?>
<?php include 'header.phtml'; ?>

<main class = "container">
  <section>
    <h1>Publications scientifiques</h1>

    <ul class="espace" >
      <li><a href="http://onlinelibrary.wiley.com/doi/10.1002/anie.201201360/abstract">Knölker's iron complex: an efficient in situ generated catalyst for reductive amination of alkyl aldehydes and amines.</a></li>

      <li><a href="http://onlinelibrary.wiley.com/doi/10.1002/chem.201302432/abstract">Bifunctional (cyclopentadienone)iron-tricarbonyl complexes: synthesis, computational studies and application in reductive amination.</a></li>

      <li><a href="http://www.sciencedirect.com/science/article/pii/S0022328X14004586">Microwave irradiation and flow chemistry for a straightforward synthesis of piano-stool iron complexes.</a></li>

      <li><a href="http://onlinelibrary.wiley.com/doi/10.1002/ejoc.201403194/abstract">Immobilization of an Anthracene-Tagged Ruthenium Complex on a 2,4,7-Trinitrofluoren-9-one-Grafted Silica: Efficiency and Recyclability in Olefin Metathesis Reactions.</a></li>

      <li><a href="https://www.researchgate.net/scientific-contributions/74098890_Anastassiya_Pagnoux-Ozherelyeva">Anastassiya Pagnoux-Ozherelyeva's scientific contributions...</a></li>
    </ul>
	</section>
</main>
<?php include 'footer.phtml'; ?>
